package fi.pss.cleanbeach.ui.views.events;

import com.vaadin.server.ClassResource;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;

import fi.pss.cleanbeach.ui.MainAppUI;
import fi.pss.cleanbeach.ui.util.Lang;
import fi.pss.cleanbeach.ui.views.eventdetails.EventDetailLayout;

/**
 * Public view for a single event. The URL for this gets generated by the Event
 * page and is typically shared through social media.
 * 
 * @author thomas
 */
public class PublicEventView extends EventDetailLayout {

	private static final long serialVersionUID = -2028979629840860535L;

	public PublicEventView(fi.pss.cleanbeach.data.Event e) {
		super(e, null);

		addStyleName("publicevent");
		setCaption(Lang.get("public.caption"));
		getNavigationBar().setRightComponent(null);

		addHeader();
		updateMembersAndComments();
		addRegisterComponents();
	}

	private void addRegisterComponents() {
		Label reg = new Label(Lang.get("public.regblurb"));
		content.addComponent(reg);

		HorizontalLayout hl = new HorizontalLayout();
		hl.setSpacing(true);
		hl.setWidth("100%");
		// hl.addStyleName("actionbuttons");
		content.addComponent(hl);

		Button register = new Button(Lang.get("public.register"));
		hl.addComponent(register);

		Button login = new Button(Lang.get("public.login"));
		hl.addComponent(login);

		register.addClickListener(new LoginListener());
		login.addClickListener(new LoginListener());
	}

	private void updateMembersAndComments() {
		creator.setValue(Lang.get("public.numvolunteers", selectedEvent
				.getOrganizer().getName(), selectedEvent.getJoinedUsers()
				.size()));

		members.setValue(Lang.get("public.numcomments", selectedEvent
				.getComments().size(), selectedEvent.getNumCommentsWithImage()));

		content.removeComponent(comments);
	}

	private void addHeader() {

		Label desc = new Label(Lang.get("login.caption.small"),
				ContentMode.HTML);
		desc.addStyleName("desc");

		Image logo = new Image();
		logo.setSource(new ClassResource("logo.png"));
		logo.setHeight("102px");
		logo.setWidth("102px");
		logo.addStyleName("logo");

		HorizontalLayout hl = new HorizontalLayout(desc, logo);
		// hl.setComponentAlignment(logo, Alignment.MIDDLE_CENTER);
		hl.setSpacing(true);
		hl.setWidth("100%");
		hl.setExpandRatio(desc, 1);
		hl.addStyleName("logolayout");
		hl.setMargin(new MarginInfo(false, false, true, false));

		Component header = hl;

		content.addComponent(header, 0);
	}

	private class LoginListener implements ClickListener {

		private static final long serialVersionUID = -8391414666637636181L;

		@Override
		public void buttonClick(ClickEvent event) {
			MainAppUI.getCurrent().loginFromPublic(selectedEvent.getId());
		}

	}

}
