package fi.pss.cleanbeach.data;

import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import com.vaadin.annotations.AutoGenerated;

@MappedSuperclass
public class AbstractEntity {

	public static final long DEFAULT_ID = -1L;

	@Id
	@AutoGenerated
	protected long id = DEFAULT_ID;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null || !(obj instanceof AbstractEntity)) {
			return false;
		}
		AbstractEntity other = (AbstractEntity) obj;

		return other.id == id;
	}

	@Override
	public int hashCode() {
		if (id != DEFAULT_ID) {
			return (int) id;
		}
		return super.hashCode();
	}
}
